from app.Prompts.buyer_mail_address_prompts import system_prompt as buyer_mail_address_system_prompt
from app.Prompts.buyer_mail_address_prompts import message_prompt as buyer_mail_address_message_prompt
from app.Prompts.buyer_mail_address_prompts import all_column_names as buyer_mail_address_all_column_names

from app.Prompts.buyer_data_prompts import system_prompt as buyer_data_system_prompt
from app.Prompts.buyer_data_prompts import message_prompt as buyer_data_message_prompt
from app.Prompts.buyer_data_prompts import all_names_column_names as buyer_names_all_column_names
from app.Prompts.buyer_data_prompts import all_desc_column_names as buyer_desc_all_column_names

from app.Prompts.seller_name_prompts import system_prompt as seller_names_system_prompt
from app.Prompts.seller_name_prompts import message_prompt as seller_names_message_prompt
from app.Prompts.seller_name_prompts import all_column_names as seller_names_all_column_names

from app.Prompts.borrower_name_prompts import system_prompt as borrower_names_system_prompt
from app.Prompts.borrower_name_prompts import message_prompt as borrower_names_message_prompt
from app.Prompts.borrower_name_prompts import all_column_names as borrower_names_all_column_names

from app.Prompts.borrower_mail_address_prompts import system_prompt as borrower_mail_address_system_prompt
from app.Prompts.borrower_mail_address_prompts import message_prompt as borrower_mail_address_message_prompt
from app.Prompts.borrower_mail_address_prompts import all_column_names as borrower_mail_address_all_column_names

from app.Prompts.property_info_prompts import system_prompt as property_info_system_prompt
from app.Prompts.property_info_prompts import message_prompt as property_info_message_prompt
from app.Prompts.property_info_prompts import all_column_names as property_info_all_column_names

from app.Prompts.main_prompts import system_prompt as main_table_system_prompt
from app.Prompts.main_prompts import message_prompt as main_table_message_prompt
from app.Prompts.main_prompts import all_column_names as main_table_all_column_names